[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ue-legacy-launcher"
version = "1.4.2"
description = "An integrated version manager for Oculus/Unreal games"
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
authors = [
  { name = "Obelous", email = "1@obelous.dev" },
]
dependencies = [
    "requests",
    "colorama",
    "pySmartDL",
    "pyyaml",
    "certifi"
]

[project.scripts]
a2ll = "ue_legacy_launcher.__main__:main"
uell = "ue_legacy_launcher.__main__:main"

[tool.setuptools.package-data]
ue_legacy_launcher = ["*.keystore"]


[tool.setuptools]
packages = ["ue_legacy_launcher"]
package-dir = {"" = "src"}

[tool.bumpversion]
current_version = "1.4.2"
commit = true
tag = true

[[tool.bumpversion.files]]
filename = "pyproject.toml"
search = "version = \"{current_version}\""
replace = "version = \"{new_version}\""

[[tool.bumpversion.files]]
filename = "src/ue_legacy_launcher/config.py"
search = "__version__ = \"{current_version}\""
replace = "__version__ = \"{new_version}\""