name: Publish to PyPI

on:
  push:
    branches:
      - main

jobs:
  build-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build tools
        run: |
          pip install --upgrade pip
          pip install setuptools build bump-my-version twine pkginfo

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Bump patch version
        run: bump-my-version bump patch --allow-dirty

      - name: Commit version bump
        run: |
          git add .
          git commit -m "chore: bump version"
          git push

      - name: Clean previous builds
        run: rm -rf dist build *.egg-info

      - name: Build package
        run: python -m build

      - name: Check metadata
        run: twine check dist/*

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/*
